# Generated by Django 5.0.1 on 2024-01-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_home_created_at_home_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='midea/img/listing_picture/')),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='images1',
            field=models.ImageField(upload_to='midea/img/home/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='images2',
            field=models.ImageField(upload_to='midea/img/home/'),
        ),
    ]
