# Generated by Django 5.0.1 on 2024-01-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_listing_picture_alter_home_images1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lost_Information_Categroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Lost_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('datelost', models.DateField()),
                ('brand', models.CharField(max_length=40)),
                ('primary_color', models.CharField(max_length=60)),
                ('Secondary_color', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('subcategory', models.ManyToManyField(to='app.lost_information_categroy')),
            ],
        ),
    ]
