# Generated by Django 5.0.1 on 2024-01-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lost_information_categroy_lost_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost_information',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='lost_information',
            name='subcategory',
            field=models.CharField(default='yes', max_length=60),
            preserve_default=False,
        ),
    ]
