# Generated by Django 5.0.1 on 2024-01-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_lost_information_subcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lost_Information_Categroy',
        ),
        migrations.AddField(
            model_name='lost_information',
            name='category',
            field=models.CharField(default='yes', max_length=60),
            preserve_default=False,
        ),
    ]
