# Generated by Django 5.0.1 on 2024-01-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_lost_information_categroy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('zipcode', models.IntegerField()),
            ],
        ),
    ]
